// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 20280b2ee2fd9328 "Cloudeo (copy)", do not edit manually */
"use client";

import { stdin_default } from "../chunks/chunk-WKSWHYC7.js";
import "../chunks/chunk-ZT45FOFS.js";
import { routes } from "../chunks/chunk-DKN24XRK.js";

// virtual:button/button-navbar
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "HelPtP4df",
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"20280b2ee2fd932826d5c79d2d58fec67f3ba9e6b6438539f575e02e4592d78f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"20280b2ee2fd932826d5c79d2d58fec67f3ba9e6b6438539f575e02e4592d78f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_navbar_default = ComponentWithRoot;
export { button_navbar_default as default };
